// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzYBhgf9bIXe58JU1xydOslnBJPlQSkio',
    appId: '1:35344426188:web:3c5c62c5962e70f9234e69',
    messagingSenderId: '35344426188',
    projectId: 'menu-demo-41144',
    authDomain: 'menu-demo-41144.firebaseapp.com',
    storageBucket: 'menu-demo-41144.appspot.com',
    measurementId: 'G-E1B3RBEC0Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlzSNNkjK-jTzFXVW52Zs3fTWXSOriLmI',
    appId: '1:35344426188:android:9060ac3d6640af41234e69',
    messagingSenderId: '35344426188',
    projectId: 'menu-demo-41144',
    storageBucket: 'menu-demo-41144.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmTGaL2AdHjOpwIuv4g4Pd0OZcTBhIxV0',
    appId: '1:35344426188:ios:b1bb4a29f51f1fa9234e69',
    messagingSenderId: '35344426188',
    projectId: 'menu-demo-41144',
    storageBucket: 'menu-demo-41144.appspot.com',
    iosClientId: '35344426188-ccj5gje7vfd104vcn5kc0rm2julvscdr.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterOcrTranslation',
  );
}
